name: dev site database init

on:
#  schedule:
#    - cron: '0 0 * * *'
  workflow_dispatch:      # 可手动触发（推荐保留）

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v7

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
        server-id: central


    - name: dev site install by quick shell
      run: sh shell/quick-dev-site-install.sh
